server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: gaotutu-backed
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gaotutu
    username: root
    password: 123456